# Generated by Django 5.2 on 2026-04-05 23:49

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipo',
            name='cantidad',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='equipo',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='equipo',
            name='fecha_registro',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='equipo',
            name='modelo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='serial',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='equipo',
            name='tipo_equipo',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='estado',
            field=models.CharField(default='activo', max_length=50),
        ),
    ]
